<div class="container">
	<div class="row">
		<div class="col-md-12 main">
			<h1>Prof. Srinivas Peeta</h1>
			<h2>Awarded: 2019</h2>
			<img src="<?=PROFILE_IMAGE_URL?>2019/Srinivas_Peeta.jpg" class="profile-thumb" alt="profile picture" />
			<p class="affiliation">
				<span>Frederick R. Dickerson Chair and Professor, School of Civil and Environmental Engineering, H. Milton Stewart School of Industrial and Systems Engineering, Georgia Institute of Technology</span><br /><span>Principal Research Faculty, Georgia Tech Research Institute</span><br /><span>1988/B.Tech/CE</span>
			</p>
			<p>Prof. Srinivas Peeta obtained his B. Tech. in Civil engineering from IIT Madras in 1988. He went on to pursue his M.S. in the same discipline at Caltech in 1989 and earned his Ph.D. in Civil Engineering (transportation) from the University of Texas, Austin.</p>
			<p>He has worked as a faculty member of the School of Civil Engineering at Purdue University during which time he has been keen to both propagate knowledge to the next generation and find its application for advancements in the US and in India. After 24 years at Purdue University, where he was also the Jack and Kay Hockema Professor from 2015-2018, Prof. Peeta is now the Frederick R. Dickerson Chair and Professor, School of Civil and Environmental engineering and H. Milton Stewart School of Industrial and Systems engineering, Georgia Tech. He has also headed various centres for studying and improving transport, which includes being the director of NEXTRANS Centre, the USDOT Federal Region 5 University Transportation Center from 2006-2018, where he dispensed duties related to research, education, outreach and administration. From 2007-2013, he served as chair of the Transportation Network Modeling Committee of the Transportation Research Board of the U.S. National Academies.</p>
			<p>His research work is prolific with over 370 technical publications, focused on the application of control theory, fundamental techniques in operations research, and advanced computational methods applied to large-scale transportation networks. His work in dynamic traffic assignment is considered a standard for research reference. He has won numerous accolades for his research, publications and mentoring. He was a special guest and distinguished participant at 'Move-Global Mobility Summit' organized by the Government of India in 2018, where he was a keynote speaker and panelist on reinventing public transport. He has also worked on programmes and curricula to train students. INFORMS Transportation Science Best Dissertation Award (1994), NSF CAREER Award (1997), Purdue's Seed for Success Award (2007-2013), ASCEWalter Huber Research Prize (2009), Visiting Distinguished Scholar, Taiwan (2009), UniSA Distinguished Researcher Award, Australia (2010), Purdue College of Engineering Mentoring Award (2012), Honorary Professor(2015) from Chongqing University of Posts and Telecommunications, China are among the numerous awards he has received for the great work he has done in his field, both as a mentor and researcher. In addition to him being decorated, five of his students have won best dissertation prizes as well as several awards.</p>
			<p>For his contribution to the field of Civil Engineering and Transportation in particular and his excellence as a research mentor, IIT Madras and its alumni are proud to confer this award upon Prof. Srinivas Peeta.</p>
		</div>
	</div>
</div>
