<div class="container">
	<div class="row">
		<div class="col-md-12 main">
			<h1>Dr. Parthasarathy Ranganathan</h1>
			<h2>Awarded: 2019</h2>
			<img src="<?=PROFILE_IMAGE_URL?>2019/Parthasarathy_Ranganathan.jpg" class="profile-thumb" alt="profile picture" />
			<p class="affiliation">
				<span>Google Distinguished Engineer,USA</span><br /><span>1994/B.Tech/EE</span>
			</p>
			<p>Dr. Parthasarathy Ranganathan graduated from IIT Madras in 1994 with a B.Tech in Electrical Engineering. He received his M.S. and Ph.D. in Electrical and Computing Engineering from Rice University. He worked at Hewlett-Packard Laboratories from 2000 to 2013 and held several positions including as HP Fellow and Chief Technologist, and led their research on next-generation systems including Project Moonshot and the Data-Centric Data Center program. As a Google Distinguished Engineer & Area Tech Lead, he is currently driving new technical directions and incubating innovations for the hardware and data centers that power all of Google's products.</p>
			<p>Dr. Ranganathan's research areas can be broadly classified as Energy Efficiency and System Architecture. He pioneered energy-adaptive displays and energy-aware user interfaces. His ideas around heterogeneous single-ISA multicore architectures are now pervasively adopted in ARM's big. LITTLE architecture designs, underpinning billions of devices. He pioneered ensemble power capping that enables oversubscription of power budget across large clusters. He has made other seminal contributions, around temperature-aware scheduling, cross-layer power management, new industry standards like JouleSort, SpecPower, and PUE.</p>
			<p>Dr. Ranganathan also executed an ambitious vision around disaggregated servers, rethinking system architectures across new system building blocks managed as federated ensembles. His notable contributions include microblade servers (the first to introduce low-power ARM processors for ultra-dense cloud servers) and memory blades (that broke the conventional co-location of computing and memory to enable a new class of in-memory workloads). At Google, he has defined a new category of software-defined hardware including pioneering novel applications of machine learning for the control plane to enable self-driving infrastructure and is leading the design of new custom silicon accelerators and new data hierarchies to accelerate Google workloads and accelerate cloud computing.</p>
			<p>Dr. Ranganathan is a fellow of the IEEE and the ACM and is a member of the ISCA and ASPLOS halls of fame. He has been featured in numerous press articles and interviews and was named one of 15 Top Enterprise Technology Rock Stars by Business Insider, and one of the top 35 Young Innovators in the world by MIT Technology Review. He is also a recipient of the prestigious ACM Maurice Wilkes award and Rice University's Outstanding Young Engineering Alumni award. He has published more than 100 technical papers, co-authored the influential book “The Datacenter as a Computer (3rd Edition)” and is a co-inventor on more than 125 patents.</p>
			<p>Dr. Ranganathan is also the founding member of the pan-IIT Alumni Association and the Secretary and Founding Director of IIT Madras Alumni Association of North America. For his groundbreaking technical innovation in the areas of energy efficiency and system architectures, IIT Madras and its alumni are proud to confer this award upon Dr. Parthasarathy Ranganathan.</p>
		</div>
	</div>
</div>
