<div class="container">
	<div class="row">
		<div class="col-md-12 main">
			<h1>Dr. Mas A. Subramanian</h1>
			<h2>Awarded: 2018</h2>
			<img src="<?=PROFILE_IMAGE_URL?>2018/Mas_A._Subramanian.JPG" class="profile-thumb" alt="profile picture" />
			<p class="affiliation">
				<span>Milton Harris Chair Professor of Materials Science, Oregon State University, USA</span><br /><span>1982/PhD/CY</span>
			</p>
			<p>Dr. Mas Subramanian is a graduate of University of Madras with Bachelor’s and Master’s degrees in Chemistry earned in 1975 and 1977, respectively. In 1982, he completed his doctoral research from IIT Madras in Materials Chemistry, and joined Texas A&M University as a Post-Doctoral Fellow. He worked at DuPont Company from 1984 to 2006 as a Research Scientist. Since 2006, he is the Milton Harris Chair Professor of Materials Science at Oregon State University.  Since 2006, he is also the Signature Faculty Fellow of Oregon Nano science and Micro technologies Institute. He has served as Director of Materials Institute, Oregon State University from 2006 to 2013.</p>
			<p>Dr. Subramanian is internationally recognized for breakthrough discoveries in the field of superconductors, dielectrics, magnetism, catalysis, thermoelectrics and inorganic pigments. His research focuses on designing new inorganic solid state functional materials for emerging applications in electronics, energy conversion and the environment. His notable discoveries include: zeolites as precursors to electronic ceramics, new Bi and Tl-containing superconductors, catalysts for Fischer-Tropsch synthesis, colossal dielectrics, colossal magnetoresistance oxides, and Skutterudite Thermoelectrics. His work on fluoro aromatic synthesis is one of his most notable achievements. Dr. Mas Subramanian's scientific discoveries have been featured in leading international newspapers and magazines such as The New York Times, National Geographic, National Public Radio, BBC News, CNN, Sydney Morning Herald, The Hindu and Times of India. In 2009, Dr. Subramanian and his team discovered a new class of highly-durable, non-toxic intense blue color pigments-based manganese oxides. This discovery of “MAS Blue” received world-wide attention since it has been over 200 years since the last durable blue pigment -- CoAl2O4 (circa. 1802) -- was discovered.</p>
			<p>Dr. Subramanian has authored 350 publications in esteemed journals such as Science, Nature, Journal of American Chemical Society, Physical Review Letters, et al., and holds 57 US patents. He has delivered more than 200 invited talks all over the world. He has been honored with many accolades, including the 2016 Oregon Academy of Science Outstanding Scientist Award, F.A. Gilfillan Memorial Award for Distinguished Scholarship in Science in 2013, Chemical Research Society of India (CRSI) International Medal in 2012, the 2012 U.S. National Science Foundation Creativity Award, and the DuPont Charles Pedersen Medal in 2004. He has also served as a visiting professor at Institut de Chimie de la Matière Condensée de Bordeaux, University of Bordeaux, France, and as the Normandy CNRS Chair of Excellence at CRISMAT Laboratory, University of Caen, France. He is the Editor of two leading international journals -- 'Solid State Sciences' and 'Progress in Solid State Chemistry'. He has also served on the Editorial Board of journals such as Chemistry of Materials, Materials Research Bulletin, and Journal of Solid State Chemistry.</p>
			<p>For his discovery of “Mas Blue” and other outstanding contributions to the field of materials chemistry, IIT Madras and its alumni are proud to confer this award upon Dr. Mas Subramanian.</p>
		</div>
	</div>
</div>
