<div class="container">
	<div class="row">
		<div class="col-md-12 main">
			<h1>Dr. Noshir S. Contractor</h1>
			<h2>Awarded: 2018</h2>
			<img src="<?=PROFILE_IMAGE_URL?>2018/Noshir_S._Contractor.JPG" class="profile-thumb" alt="profile picture" />
			<p class="affiliation">
				<span>Jane S. &amp; William J. White Professor of Behavioral Sciences, Northwestern University, USA</span><br /><span>1983/BT/EE</span>
			</p>
			<p>Dr. Noshir S. Contractor graduated from IIT Madras in 1983 with a Bachelor’s degree in Electrical Engineering. He received his Master's degree in Communication from the Annenberg School of Communication at the University of Southern California where he also carried out his doctoral research in Communication, obtaining his Ph.D. in 1987. Having served on the faculty of University of Illinois at Urbana-Champaign till 2007, he is currently the Jane S. &amp; William J. White Professor of Behavioral Sciences at Northwestern University, USA.</p>
			<p>Dr. Contractor is well known for the Multi-Theoretical Multi-Level (MTML) Framework he developed along with Peter Monge. This is described in detail in his book, “Theories of Communication Networks”, which received the 2003 Book of the Year award from the Organizational Communication Division of the National Communication Association. He was also one of the principal investigators of the Virtual Worlds Observatory project, and has          co-edited a book on “Predicting Real World Behaviors from Virtual World Data” in 2014.</p>
			<p>His contributions to the field of behavioral sciences and communication are numerous and outstanding, and he has been described by Sir Tim Berners-Lee, one of the world-renowned inventors of the World Wide Web (WWW), as “a true intellectual leader and curator of the web community”. Dr. Contractor has presented and published more than 250 research papers in international conferences and esteemed journals in the area of social communication networks, and has contributed chapters to prominent books. The long list of honors and accolades received by him includes: International Communication Association Fellow in 2015; National Communication Association Distinguished Scholar Award in 2014; and Outstanding Member Award, Organizational Communication Division, International Communication Association, in 2000.</p>
			<p>Dr. Contractor has been part of software development projects such as Recommender system for scaling up health innovations in Bihar, India and the assembly of interdisciplinary teams. Recently, he has been funded by the Bill &amp; Melinda Gates Foundation to develop “Novel Approaches to Measuring Demand-side Community Perceptions and Barriers to Family Planning via Social Network Analysis” in Kenya, and by the National Aeronautics &amp; Space Administration (NASA) to design, monitor and mitigate against challenges that will be faced by international crews on missions to Mars. He serves on the Board of Trustees for the Web Science Trust and has served on many Advisory Boards, including the European Union FP7 Network of Excellence in Internet Science–EINS, Canadian Health Services Research Foundation and the US National Academies of Science (NAS) Decadal Survey of Social and Behavioral Sciences and Applications to National Security. He has held external university appointments at Stanford University's School of Engineering, Columbia University's Center for Organizational Innovation and Fudan University's School of Management in Shanghai.</p>
			<p>For his revolutionary contributions to computational social science, social networks and human communication systems, IIT Madras and its alumni are proud to confer this award upon Dr. Noshir S. Contractor.</p>
		</div>
	</div>
</div>
