<div class="container">
	<div class="row">
		<div class="col-md-12 main">
			<h1>Dr. Seeram Ramakrishna</h1>
			<h2>Awarded: 2018</h2>
			<img src="<?=PROFILE_IMAGE_URL?>2018/Seeram_Ramakrishna.jpg" class="profile-thumb" alt="profile picture" />
			<p class="affiliation">
				<span>Professor and Director, Center for Nanofibers and Nanotechnology, Dept. of Mechanical Engineering, National University of Singapore, Singapore</span><br /><span>1988/MT/Aircraft Production (ME)</span>
			</p>
			<p>Dr. Seeram Ramakrishna graduated with a Master’s degree from IIT Madras in 1988, after having obtained a Bachelor of Engineering Degree from Andhra University. Subsequently, he pursued a Ph.D. from the University of Cambridge, UK, and the General Management Program from Harvard University, USA. He is currently a Professor and Director of the Center for  Nanofibers and Nanotechnology in the Department of Mechanical Engineering, National University of  Singapore (NUS).</p>
			<p>Dr. Ramakrishna's leadership experience includes NUS' University Vice-President (Research Strategy); Dean of Faculty of Engineering; Director of NUS Enterprise; Director of NUS Industry Liaison Office; Founding Director of NUS Bioengineering; Founding Director of NUS Nanoscience & Nanotechnology Initiative, NUSNNI; Founding Chairman of Solar Energy Research Institute of Singapore, SERIS; and Chair of Circular Economy Taskforce.</p>
			<p>Dr. Ramakrishna is an elected International Fellow of Royal Academy of Engineering, UK; Academy of Engineering, Singapore; National Academy of Engineering, India; ASEAN Academy of Engineering & Technology; ISTE, India; Institution of Engineers Singapore (IES); American Association for the Advancement of Science (AAAS); ASM International; American Society for Mechanical Engineers (ASME); American Institute for Medical & Biological Engineering (AIMBE); ImechE and IoM3, UK; and International Union of Biomaterials Science & Engineering (FBSE).</p>
			<p>Dr. Ramakrishna is a highly-cited researcher in Materials Science. Thomson Reuters recognized him among the “World's Most Influential Scientific Minds”, and a European study placed him among only five researchers from Singapore with H-index above 100. He has co-authored more than 1,000 SCI-listed international journal papers and five books, which have received in excess of 74,000 citations and H-Index of 127. He is among the world's foremost scientists working on nanomaterials by electrospinning. His work has resulted in patented technologies which are translated into real world products. He advises technology start-ups and investors. He is an Editorial Board member of ten international journals, and an Editor of Elsevier Journal of Current Opinion in Biomedical Engineering.</p>
			<p>Dr. Ramakrishna is a Nominated Member of the World Economic Forum Committee on Future of Production-Sustainability. He chairs the Future of Manufacturing TC at the Institution of Engineers, Singapore. He advises Singapore's National Environmental Agency on Circular Economy and Industry 4.0. He authored the book “The Changing Face of Innovation”. He is an op-ed columnist and regular speaker on higher education, research and innovation at forums facilitated by United Nations Academic Impact, World Bank, Asian Development Bank, OECD, and UNESCO. Over the past 15 years, he has been serving the global engineering community in various capacities including: Founding Chair of Global Engineering Deans; Vice-President of IFEES; and Board Member of Asia Society for Innovation & Policy.</p>
			<p>Dr. Ramakrishna has received several awards and other forms of recognition for his pioneering research contributions, and among these are: 'Fibernamics Award' in Portugal, International Federation of Engineering Educator Societies (IFEES) President's Award as a 'Global Visionary'; and ASEAN Outstanding Engineer Award.</p>
			<p>For his visionary work in the fields of nano materials technology and engineering education, IIT Madras and its alumni are proud to confer this award on Dr. Seeram Ramakrishna.</p>
		</div>
	</div>
</div>
