<div class="container">
	<div class="row">
		<div class="col-md-12 main">
			<h1>Dr. Giridhar Madras</h1>
			<h2>Awarded: 2018</h2>
			<img src="<?=PROFILE_IMAGE_URL?>2018/Giridhar_Madras.jpg" class="profile-thumb" alt="profile picture" />
			<p class="affiliation">
				<span>Professor of Chemical Engineering, Indian Institute of Science, Bangalore</span><br /><span>1990/MT/CH</span>
			</p>
			<p>Dr. Giridhar Madras graduated from IIT Madras with a Master’s degree in Chemical Engineering in 1990, having earlier obtained a Bachelor’s degree from Annamalai University. He obtained his Ph.D. in 1993 from Texas A&M University, USA, and moved on to postdoctoral research at the University of California, Davis. He returned to India as an Assistant Professor of Chemical Engineering at the Indian Institute of Science, Bangalore in 1998. Since 2007, he has been a Full Professor of the Department. He is also an Associate Faculty in Solid State and Structural Chemistry and the Chairman of the Interdisciplinary Center for Energy Research.</p>
			<p>Dr. Giridhar has made pioneering contributions to several areas of polymer degradation, development of new catalysts, and in the application of continuous distribution kinetics to various processes. His research interests span the area of reaction engineering applied to polymers, supercritical fluids, and catalysis. His research group focuses on reaction kinetics, as applied to various systems and processes. His work has resulted in many publications and citations in addition to having a direct impact on industry. This has resulted in more than 500 publications, 15,000 citations and a h-index of 55, the highest among all engineering faculty in India. In addition, he has several patents that have resulted in commercialization of revolutionary new catalysts in various industrial processes. He has successfully executed various projects worth several crores from governmental agencies such as DST, DBT, etc., and from industries such as BHEL, FMC, GAIL, etc. He has graduated 40 Ph.D. students, 40 Master’s students and guided more than 30 summer interns. Many of his students are currently faculty in IITs, IISERs and NITs. He is currently the Associate Editor of several journals including RSC Advances, Advanced Powder Technology, Bulletin of Material Science, Current Science, and International Journal of Polymer Science.</p>
			<p>Dr. Giridhar has been awarded various Fellowships and Awards for his excellence in teaching and research. These include Fellowships of the Indian National Science Academy, Indian National Academy of Engineering, Indian Academy of Sciences and the National Academy of Science of India. He was deemed a “J. C. Bose National Fellow” in 2015. He received the 2015 IISc Excellence Award in Teaching and Research, and the S. S. Bhatnagar Prize awarded by CSIR in 2009. He was also awarded the Swarnajayanthi Fellowship by DST in 2006, and was listed among the top 1% of scientists by the ISI Web of Knowledge. In addition to scientific research, he writes a popular blog, and maintains a website that answers questions for prospective faculty who want to return to India.</p>
			<p>For his sustained excellence in teaching and research in chemical engineering, IIT Madras and its alumni are proud to confer this award upon Dr. Giridhar Madras.</p>
		</div>
	</div>
</div>
