	<div class="container">
	<div class="row">
		<div class="col-md-12 main">
			<h1>Prof. Kaushik Bhattacharya</h1>
			<h2>Awarded: 2019</h2>
			<img src="<?=PROFILE_IMAGE_URL?>2019/Kaushik_Bhattacharya.jpg" class="profile-thumb" alt="profile picture" />
			<p class="affiliation">
				<span>Howell N. Tyson Sr. Professor of Mechanics and Professor of Materials Science and Vice Provost( Research),California Institute of Technology, USA</span><br /><span>1986/B.Tech/ME</span>
			</p>
			<p>Kaushik Bhattacharya is Howell N. Tyson, Sr., Professor of Mechanics and Professor of Materials Science as well as Vice-Provost (Research) at the California Institute of Technology. He received his B. Tech. degree from the Indian Institute of Technology Madras in 1986, his Ph.D. from the University of Minnesota in 1991 and received post-doctoral training at the Courant Institute for Mathematical Sciences during 1991-1993. He joined Caltech in 1993. He has held visiting positions at Cornell University, Heriot-Watt University in Scotland, Max-Planck-Institute at Leipzig, Isaac Newton Institute at the University of Cambridge, Indian Institute of Science at Bangalore, the Jet Propulsion Laboratory and the University of Cambridge.</p>
			<p>He is internationally recognized for his contributions to understanding the mechanics and physics active materials, including shape-memory alloys, ferroelectrics and nematic elastomers, the mechanics of heterogeneous materials, fracture and failure and multiscale modelling. His 140+ publications and 3+ patents have had a major impact on education, research and industrial practice in engineering sciences – in particular on the disciplines of Mechanical Engineering and Materials Sciences as well as Applied Mathematics. Bhattacharya has received the Warner T. Koiter Medal of the American Society of Mechanical Engineering, Young Investigator Prize from the Society of Engineering Science, the Special Achievements Award in Applied Mechanics from the American Society of Mechanical Engineers and the National Science Foundation Young Investigator Award. He is a fellow of the Society of Industrial and Applied Mathematics. He is a recipient of the Graduate Student Council Teaching and Mentoring Award at Caltech. He has delivered numerous plenary, keynote and named lectures including the Midwest Mechanics Lecturer for 2006-07 (10 universities), Southwest Mechanics Lecturer for 2007-08 (5 universities) and Spanish Mechanics Lecturer in 2013 (5 universities).</p>
			<p>He served as the fifth editor of the prestigious Journal of the Mechanics and Physics of Solids from 2004 to 2015. Currently, he serves on the editorial board of the Archive for Rational Mechanics and Analysis. He has served on the Board of Directors of the Society of Engineering Science and is the founding Program Director of the SIAM Activity Group on the Mathematical Aspects of Materials Science. Since 2008, he has been the Executive Officer of the Department of Mechanical and Civil Engineering. He has supervised 29 doctoral students, mentored 22 postdoctoral scholars and hosted numerous visiting scholars, many of whom hold leadership positions in academics, industry and national laboratories. He has served as a consultant for Boston Scientific Corporation, advising them on the design of super-elastic implantable medical devices, assisted AGA Medical Corporation in interviewing and recruiting research engineers and helping them develop an in-house expertise in shape-memory and superelastic technologies, provided training for engineers at Oromco who were involved in developing a new class of orthodontic wires and assisted Medtronic Inc. in developing a core-competence in shape-memory alloys. He is currently working with the Nitinol Development Corporation on the fatigue of these materials.</p>
			<p>For his ground-breaking achievements in education, research and industrial practice in Mechanical Engineering and Materials Sciences, IIT Madras and its alumni are proud to confer this award upon Kaushik Bhattacharya.</p>
		</div>
	</div>
</div>
