<div class="container">
	<div class="row">
		<div class="col-md-12 main">
			<h1>Dr. D. V. Satya Gupta</h1>
			<h2>Awarded: 2018</h2>
			<img src="<?=PROFILE_IMAGE_URL?>2018/D._V._Satya_Gupta.JPG" class="profile-thumb" alt="profile picture" />
			<p class="affiliation">
				<span>Technology Fellow, Baker Hughes, USA</span><br /><span>1974/BT/CH</span>
			</p>
			<p>Dr. D. V. Satya Gupta graduated from IIT Madras in 1974 with a Bachelor’s degree in Chemical Engineering. He obtained Master of Science and Doctor of Science degrees in Chemical Engineering from Washington University, U.S., in 1976 and 1979, respectively. Dr. Gupta is one of the world's preeminent experts on well stimulation technology including fracturing, which, along with horizontal drilling, has made the US almost self-sufficient in energy in recent years. He is a prolific inventor whose inventions and co-inventions have resulted in more than 150 U.S. and international patents in application of chemical technology for oil and gas production enhancement. He is also the author of more than 70 technical papers and co-author of Chapters on 'fracturing fluids' in several books. Since 2015, he is a Technology Fellow at Baker Hughes, a GE company.</p>
			<p>Prior to his service at Baker Hughes and affiliated companies, Dr. Gupta had diverse appointments and responsibilities at reputed firms and institutes such as Gulf South Research Institute and Pennzoil Technology Center. His technological developments in the field of chemical engineering include: encapsulated breakers, polymer-specific enzyme breakers, long-term release production assurance products, premium performance aqueous fluid systems, non-aqueous fluid systems, and ultra-light weight proppants. Currently, along with an elite group of two other technology experts, he consults with executive management on technology matters, and mentors technical talent at one of the largest oil field service companies in the world. For his contributions to the industry and company, he was awarded the Baker Hughes Lifetime Achievement Award in 2012, one of only 12 who have been honored with this accolade during the 108-year history of this esteemed company.</p>
			<p>Industrial contributions apart, his academic endeavours are exemplified in being an active member of the American Chemical Society, American Institute of Chemical Engineers, National Association of Corrosion Engineers and Society of Petroleum Engineers. He was the 2014-15 Society of Petroleum Engineers' Distinguished Lecturer on the topic of “How to Frac with little or no water”, a topic on which he has given seminars around the world. He was awarded the 2017 Society of Petroleum Engineers' International Completions Optimization and Technology Award for his work in the area of fracturing. He has chaired several symposia on Green Corrosion Inhibitors and Fracturing Fluids, and co-Chaired the 2016 American Society of Mechanical Engineers' Hydraulic Fracturing Conference. He is on the Editorial Board of SPE technical journals, and the Hydraulic Fracture Quarterly Technical Journal. At the behest of the U.S. Department of Energy, he has been on the Industry Advisory Committee for the University of Oklahoma Fracturing Fluid Characterization Facility. He has presented at U.S. Environmental Protection Agency's Hydraulic Fracturing Study Group as an invited speaker on “Unconventional Fracturing Fluids”.</p>
			<p>For his singular contributions to the development of well-simulation and fracturing technology, IIT Madras and its alumni are proud to confer this award upon Dr. D. V. Satya Gupta.</p>
		</div>
	</div>
</div>
