<div class="container">
	<div class="row">
		<div class="col-md-12 main">
			<h1>Shri Ashish Dikshit</h1>
			<h2>Awarded: 2019</h2>
			<img src="<?=PROFILE_IMAGE_URL?>2019/Ashish_Dikshit.jpg" class="profile-thumb" alt="profile picture" />
			<p class="affiliation">
				<span>Managing Director, Aditya Birla Fashion and Retail Limited, India</span><br /><span>1990/B.Tech/EE</span>
			</p>
			<p>Shri Ashish Dikshit graduated from IIT Madras with a Bachelor's degree in Electrical Engineering in 1990. In 1992, he got his Post Graduate Diploma in Management from IIM Bangalore and subsequently completed the Advanced Management Program at Harvard Business School. Shri Ashish Dikshit started his career in Asian Paints and was one of the youngest branch managers trusted with turning around two complex, issue-ridden, under-performing branches in Guwahati and then in Kolkata.</p>
			<p>Subsequent to his stint with Asian Paints, he has spent a large part of his career in the fashion retail industry. After working across multiple roles across sales, marketing, supply chain and strategy,           Shri Ashish became the CEO of Madura Garments in 2012 and led its rapid growth by developing India's leading fashion brands such as Louis Philippe, Van Heusen, Allen Solly and Peter England through product and brand extensions as well as rapid retail expansion. Under his leadership, the company strengthened its position as India's largest branded apparel business by more than tripling its turnover and profits over next 5 years. Shri Ashish is currently the Managing Director of Aditya Birla Fashion and Retail Ltd (ABFRL), a company formed by merging different fashion businesses of Aditya Birla Group. He is today looked upon as the tallest leader in the fashion and retail industry. He has contributed to the industry actively through retail forums, engagement with the government and regulatory bodies, especially during the GST mandate and transition phase, and by developing and mentoring young people who have gone on to leadership roles within the group and through the industry. Shri Ashish was honoured with the "Outstanding Leader Award” in the year 2011 by the Chairman of Aditya Birla Group.</p>
			<p>In his earlier stint as the Principal Executive Assistant to the Chairman of Aditya Birla Group, Shri Ashish built a strong knowledge network across multiple industry sectors, ranging from manufacturing businesses such as metals, cement and specialty chemicals to consumer businesses such as Telecom, Financial Services and Retail. As part of the Group Central Cell for Strategy, he played a key role in several group level initiatives on vision and corporate planning, and HR and culture building initiatives to build a passionate, cohesive people organization across diverse companies of Aditya Birla Group.</p>
			<p>Shri Ashish has a unique leadership style which various stakeholders refer to as “strong leadership with a soft touch”. He has seen difficult business cycles and demonstrated resilience and mental toughness in the face of adversity. The business cycles and the external environment have not made him waver from the vision course he has helped set for his businesses. He is a risk taker with high standards and a clear focus. With this vision, he has taken big bets throughout his career – on people, on partnerships, on how the retail industry will pan out. He values authenticity and humaneness above all else. While having trained to value IQ, he epitomizes EQ and brings out the best in people and has stayed humble through successes and achievements.</p>
			<p>For demonstrating exceptional managerial and leadership abilities and achievements, IIT Madras and its alumni are proud to confer this award upon Shri Ashish Dikshit.</p>
		</div>
	</div>
</div>
